# This is a basic workflow to help you get started with Actions

name: Quali Torque ssm
with:
  space: SE-Candidate-Exercise-MM
  torque_token: ${{ secrets.TORQUE_TOKEN }}
  blueprint_name: ssm
  environment_name: MartinMarcan
  
on:
  workflow_dispatch:
    inputs:
      name: githubName
job:
  deployment:
     runs-on: ubuntu-latest
      steps:
        - name: Deploy Stage
          uses: fjogeleit/http-request-action@v1
          with:
            URL: 'https://qtorque.io/api/spaces/{space_name}/environments'
            method: 'POST'
            bearerToken: 
            data:{
  "sandbox_name": "string",
  "environment_name": "string",
  "blueprint_name": "string",
  "description": "string",
  "owner_email": "string",
  "collaborators": {
    "collaborators_emails": [
      "string"
    ],
    "all_space_members": true
  },
  "automation": true,
  "scheduled_end_time": "2019-08-24T14:15:22Z",
  "duration": "string",
  "source": {
      "blueprint_name": "string",
      "repository_name": "string",
      "branch": "string",
      "commit": "string"
    },
  "visibility": "string",
  "notes": "string",
  "workflows": [
    {
      "name": "string",
      "schedules": [
        {
          "scheduler": "string",
          "overridden": true
        }
      ],
      "inputs_overrides": {
        "property1": "string",
        "property2": "string"
      }
    }
  ],
  "inputs": {
    "property1": "string",
    "property2": "string"
  },
  "tags": {
    "property1": "string",
    "property2": "string"
  },
  "compute_availability": 0
}
        
