# This is a basic workflow that is manually triggered

name: Quali Troque env spin 

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'ssm name'
        default: 'Martin - y'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  spin-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: hello
      run: echo "Hello ${{ inputs.name }}" \ 
    
    - name: test
      run: curl ifconfig.me

    - name: launch env
      run: | 
            curl --request POST \
                --url https://portal.qtorque.io/api/spaces/SE-Candidate-Exercise-MM/environments \
                --header 'Authorization: Bearer ${{ secrets.TORQUE_TOKEN }}' \
                --header 'Content-Type: application/json' \
                --data '{ \
                          sandbox_name: "ssm-20230909T16081254", \
                          blueprint_name: "ssm", \
                          owner_email: "avi.marcan@gmail.com", \
                          collaborators:{collaborators_emails: [], all_space_members: false}, \
                          source: {is_editable: true, repository_name: "qtorque"}, \
                          duration: "PT2H", \
                          automation: false, \
                          inputs: {AWS_ACCESS_KEY: "{{ .params.SE_Candidate_AWS_ACCESS_KEY }}", \
                                    AWS_SECRET_KEY: "{{ .params.SE_Candidate_AWS_SECRET_KEY }}", \
                                    agent: "Quali", \ 
                                    aws_region: "us-west-2", \
                                    name: "test_martin2", \ 
                                    value: "test_martin3" \
                                  } \ 
                          artifacts: {} , \
                          all_space_members: false, \
                          collaborators_emails: [], \
                          notes: "", \                          
                          tags: {activity_type: "other"}, \
                          workflows: [] \
                          }'
