# This is a basic workflow that is manually triggered

name: Quali Troque env launch 

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'ssm name'
        default: 'Martin - x'
        required: true
        type: string


jobs:
  spin-env:
    runs-on: ubuntu-latest
    steps:
    - name: hello
      run: echo "Hello ${{ inputs.name }}" \ 

    - name: launch env
      run: | 
            curl --request POST \
                --url https://portal.qtorque.io/api/spaces/SE-Candidate-Exercise-MM/environments \
                --header 'Authorization: Bearer ${{ secrets.TORQUE_TOKEN }}' \
                --header 'Content-Type: application/json' \
                --data '{"sandbox_name": "${{ inputs.name }}", "blueprint_name": "ssm",  "owner_email": "avi.marcan@gmail.com",  "collaborators":{"collaborators_emails": [], "all_space_members": false},  "source": {"is_editable": true, "repository_name": "qtorque"},  "duration": "PT2H",  "automation": false,  "inputs": {"AWS_ACCESS_KEY": "{{ .params.SE_Candidate_AWS_ACCESS_KEY }}", "AWS_SECRET_KEY": "{{ .params.SE_Candidate_AWS_SECRET_KEY }}", "agent": "Quali", "aws_region": "us-west-2", "name": "test_martin2", "value": "test_martin3" } ,"artifacts": {} ,  "all_space_members": false,  "collaborators_emails": [],  "notes": "", "tags": {"activity_type": "other"},  "workflows": []}'
