name: Quali Troque env spin 

on:
  repository_dispatch:
    inputs:
      name:
        description: 'ssm name'
        default: 'Martin Env'
        required: true
        type: string

jobs:
  spin-torque:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}" | 
           curl ---request POST \
                --url https://portal.qtorque.io/api/spaces/space_name/environments \
                --header 'Authorization: Bearer ${{ secrets.TORQUE_TOKEN }}' \
                --header 'Content-Type: application/json' \
                --data '{
                          sandbox_name: "ssm-20230909T16081254",
                          blueprint_name: "ssm", 
                          owner_email: "avi.marcan@gmail.com",
                          artifacts: {} ,
                          automation: false,
                          blueprint_name: "ssm",
                          collaborators:{collaborators_emails: [], all_space_members: false},
                          all_space_members: false,
                          collaborators_emails: [],
                          duration: "PT2H",
                          inputs: {AWS_ACCESS_KEY: "{{ .params.SE_Candidate_AWS_ACCESS_KEY }}",
                                   AWS_SECRET_KEY: "{{ .params.SE_Candidate_AWS_SECRET_KEY }}"}
                          agent: "Quali",
                          aws_region: "us-west-2",
                          name: "test_martin2",
                          value: "test_martin3",
                          notes: "",
                          owner_email: "avi.marcan@gmail.com",
                          sandbox_name: "ssm-20230909T16081254",
                          source: {is_editable: true, repository_name: "qtorque"},
                          tags: {activity_type: "other"},
                          workflows: []
                          }'
