# This is a workflow that is manually triggered for starting ssm environment

####################################
# Workflow Metadata
###################################
name: Manual Deploy SSM environment


#################################
# workflow inputs
################################

on:
  workflow_dispatch:
    inputs:
      space:
        description: 'The name of the Torque Space your repository is connected to'
        type: string
        required: true
        default: SM-SE-Candidate-Exercise
      blueprint_name:
        description: 'Provide blueprint name'
        type: string
        required: false
        default: ssm
      environment_name:
        description: 'Provide environment name'
        type: string
        required: false
        default: ssm_for_se_env_1
      repo_name:
        description: 'default repository name'
        type: string
        required: true
        default: qtorque
      aws_region:
        description: 'AWS default region'
        type: string
        required: true
        default: us-east-1
      ssm_name:
        description: 'Provide ssm key name name'
        type: string
        required: true
        default: ssm_key_name
      ssm_value:
        description: 'Provide ssm value'
        type: string
        required: true
        default: ssm_value_for_Shay_se

######################
# Jobs
######################
jobs:
  Test-inputs:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Got the following inputs- ${{ secrets.TORQUE_TOKEN }}, ${{secrets.AWS_ACCESS_KEY }}, ${{ secrets.AWS_SECRET_KEY }}, ${{ inputs.aws_region }}"
        
  test-ssm-with-torque:
    runs-on: ubuntu-latest
    steps:
    - name: test-ssm-with-torque
      id: start-env
      uses: QualiTorque/torque-start-environment@v1
      with:
        space: ${{ inputs.spcae }}
        torque_token: "${{ secrets.TORQUE_TOKEN }}"
        blueprint_name: ${{ inputs.blueprint_name }}
        repository_name: ${{ inputs.repo_name }}
        inputs: 'aws_region="${{ inputs.aws_region }}",name="${{ inputs.ssm_name }}",value="${{ inputs.ssm_value }}",agent="Quali", AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}",AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}"'
        torque_hostname: "portal.qtorque.io"
        timeout: 15
        duration: 60
    outputs:
          environment_name: ${{ inputs.environment_name }}
          environment_id: ${{ steps.test-ssm-with-torque.outputs.environment_id }}