####################################
# Workflow Metadata
###################################
name: Torque SSM environment with curl


###################################
# workflow inputs
###################################

on:
  workflow_dispatch:
    inputs:
      space:
        description: 'The name of the Torque Space your repository is connected to'
        type: string
        required: true
        default: SM-SE-Candidate-Exercise
      sendbox:
        description: 'The name of the Torque sendbox'
        type: string
        required: true
        default: shay_se_sandbox
      blueprint_name:
        description: 'Provide blueprint name'
        type: string
        required: false
        default: ssm
      environment_name:
        description: 'Provide environment name'
        type: string
        required: false
        default: ssm_for_se_env_1
      repo_name:
        description: 'default repository name'
        type: string
        required: true
        default: qtorque
      aws_region:
        description: 'AWS default region'
        type: string
        required: true
        default: us-east-1
      ssm_name:
        description: 'Provide ssm key name name'
        type: string
        required: true
        default: ssm_key_name
      ssm_value:
        description: 'Provide ssm value'
        type: string
        required: true
        default: ssm_value_for_Shay_se

######################
# Jobs
######################
jobs:
